- name: Update igel servers
  hosts: igelftp
  remote_user: root

  tasks:
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day